
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_score;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_score(
  user_id INTEGER NOT NULL PRIMARY KEY,
  score INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
  FOREIGN KEY (user_id) REFERENCES user (id)
);


